# Generated by Django 5.1.6 on 2025-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='projects',
            field=models.TextField(max_length=200),
        ),
    ]
